name: Remove PDF Watermark

on:
  push:
    branches:
      - main  # Adjust to your preferred branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  remove-watermark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust the Python version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyMuPDF requests

      - name: Download PDF and Remove Watermark
        run: python remove_watermarks.py

      - name: Upload Modified PDF
        uses: actions/upload-artifact@v2
        with:
          name: modified-pdf
          path: output.pdf  # The output PDF with removed watermarks
